<a href="https://colab.research.google.com/github/Shambhuraje1919/CODEVERTEX/blob/main/Time_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import datetime
import pandas as pd
import numpy as np

In [8]:
today = datetime.datetime.today()

In [9]:
today

datetime.datetime(2026, 6, 14, 14, 32, 59, 792026)

In [10]:
path = "/content/messages.csv"

In [11]:
df = pd.read_csv(path)

In [15]:
df.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [14]:
df.describe()

                       date                                          msg
count                  1000                                         1000
unique                  999                                          966
top     2013-11-01 23:36:00  ласковая кошечка ищет своего ночного котика
freq                      2                                            4

In [16]:
df.columns

Index(['date', 'msg'], dtype='object')

In [23]:
# Converting to datetime datatype
df['date'] = pd.to_datetime(df['date'])

In [24]:
df.head(2)

                 date                                               msg
0 2013-12-15 00:50:00                          ищу на сегодня мужика 37
1 2014-04-29 23:40:00  ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826

In [27]:
df["hour"] = df["date"].dt.hour
df["min"] = df["date"].dt.minute
df["sec"] = df["date"].dt.second

In [28]:
df.head(2)

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0

In [56]:
df['day'] = df['date'].dt.day_name()
df['month'] = df['date'].dt.month_name()
df['year'] = df['date'].dt.year
df['leap_year'] = df['date'].dt.is_leap_year

In [57]:
df.head(2)

,date,msg,hour,min,sec,day,week,month,year,year_end,leap_year
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,Sunday,6,December,2013,False,False
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,Tuesday,1,April,2014,False,False

In [58]:
df["time"] = df['date'].dt.time

In [59]:
df.head(2)

,date,msg,hour,min,sec,day,week,month,year,year_end,leap_year,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,Sunday,6,December,2013,False,False,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,Tuesday,1,April,2014,False,False,23:40:00

In [61]:
print("You can use this in varius machine learning algo for a secure and easy ecections")

You can use this in varius machine learning algo for a secure and easy ecections